language: python
python:
  - "3.6"
  - "nightly"

# command to install dependencies
install:
  - "pip install -e . --upgrade"
  - "pip install pipenv"
  - "pipenv install --dev"

# command to run tests
script:
  - pipenv run python -m pytest tests # or py.test for Python versions 3.5 and below
  - pipenv run python -m coverage run --source pylaas_core -m py.test
  - pipenv run python -m coverage report -m

after_success:
  - coveralls

notifications:
  email:
    recipients:
      - fs@agidev.fr
