language: python
python:
  - "3.6"
  - "nightly"

# command to install dependencies
install:
  - "pip install -e . --upgrade"
  - "pipenv install --dev"

# command to run tests
script:
  - pytest # or py.test for Python versions 3.5 and below