language: python
python:
  - "3.6"
  - "nightly"

# command to install dependencies
install:
  - "pip install -e . --upgrade"
  - "pip install pipenv"
  - "pipenv install --dev"

# command to run tests
script:
  - pytest
after_success:
  - coveralls

notifications:
  email:
    recipients:
      - fs@agidev.fr
